version: '3.9'
services:
  minio-server:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
      - MINIO_SITE_NAME
      - MINIO_SITE_REGION
    ports:
      - "9000:9000"
      - "9001:9001"
    command: [ "server", "/data", "--console-address", ":9001" ]
    volumes:
      - minio-bucket:/data

  postgres:
    image: postgres:14.2
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  minio-bucket:
  pg_data:
