apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - ../services/backend
  - ../services/frontend

components:
  - ../components/minio
  - ../components/ingress
