GET {{host}}:{{port}}{{context-path}}/api/v1/minio/bucket/exists

### check bucket is exists

POST {{host}}:{{port}}{{context-path}}/api/v1/minio/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="honda-cbr1000rr.jpg"
Content-Type: application/octet-stream

< ./honda-cbr1000rr.jpg

--WebAppBoundary
Content-Disposition: form-data; name="folder";
Content-Type: application/x-www-form-urlencoded

images

### upload file

POST {{host}}:{{port}}{{context-path}}/api/v1/minio/preview
Content-Type: application/json

{
  "objectId": "images/a4159524-573c-4320-9303-46bcbf354417.jpg",
  "duration": 1,
  "unit": "HOURS"
}

### presigned url from object id
