minio:
  bucket:
    name: ${MINIO_BUCKET_NAME:example-apps}
  endpoint:
    url: ${MINIO_ENPOINT_URL:http://localhost}
    port: ${MINIO_ENDPOINT_PORT:9000}
    secure: ${MINIO_ENDPOINT_SECURE:false}
  region:
    name: ${MINIO_REGION_NAME:sa-east-1}
    enabled: ${MINIO_REGION_ENABLE:false}
  credential:
    access_key: ${MINIO_CRED_ACCESS_KEY:admin}
    secret_key: ${MINIO_CRED_SECRET_KEY:admin123}
spring:
  mvc:
    dispatch-options-request: true
    dispatch-trace-request: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 200MB
      resolve-lazily: true
storage:
  files:
    location: ${STORAGE_FILE_LOCATION:./target/uploads}
server:
  port: ${APPLICATION_PORT:8080}
