minio:
  bucket:
    name: ${MINIO_BUCKET_NAME:example-apps}
  endpoint:
    url: ${MINIO_ENPOINT_URL:http://localhost}
    port: ${MINIO_ENDPOINT_PORT:9000}
    secure: ${MINIO_ENDPOINT_SECURE:false}
  region:
    name: ${MINIO_REGION_NAME:south-asia1-a}
    enabled: ${MINIO_REGION_ENABLE:false}
  credential:
    access_key: ${MINIO_CRED_ACCESS_KEY:admin}
    secret_key: ${MINIO_CRED_SECRET_KEY:admin123}
spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:password}
    username: ${DATABASE_USERNAME:example_minio}
    password: ${DATABASE_PASSWORD:example_minio}
  flyway:
    baseline-on-migrate: true
    enabled: false
